### ISSUE TITLE
Collapsing a group leaves one row showing, feature or bug?

### ISSUE THREAD

**Issue by dedward3** [6pac/SlickGrid#38] opened 2016-07-07 13:40 UTC
I currently have a nested grouping setup. When I minimize a 2nd level grouping it leaves one data row showing, and when I minimize a top level grouping it levels one of the 2nd level groupings showing. Just curious if this is seen as a feature or bug?

![1stlevelcollapse](https://cloud.githubusercontent.com/assets/7419302/16655116/e0a6b4ee-4426-11e6-8eab-c9e5593cb21c.JPG)

Note: the data that is visible here actually should be grouped under the 1st grouping, not the second. 
![2ndlevelcollapse](https://cloud.githubusercontent.com/assets/7419302/16655117/e0a8e336-4426-11e6-85ee-ff0e624e1170.JPG)

**Comment by 6pac** [comment] 2016-07-07 14:20
That looks like a bug. 
I remember something like this was fixed a long time ago. Perhaps we need to revisit it.
If it's not clear where the problem is, I think I have a personal branch where it might be fixed.

**Comment by dedward3** [comment] 2016-07-07 19:09
I'll take a look into it and try and figure out where it's deviating. Can you point me in the direction of where aggregation and rendering occur in SlickGrid?

**Comment by 6pac** [comment] 2016-07-08 00:28
That stuff's in ```slick.dataview.js```, the totalling around ```addTotals()``` and eventually the tree is flattened into rows for display at ```flattenGroupedRows()```

**Comment by 6pac** [comment] 2016-07-08 01:01
would be interested if you can tweak the settings on the example page to reproduce this issue

**Comment by dedward3** [comment] 2016-07-08 13:19
Okay, I'll see if I can reproduce it later today and let you know.

**Comment by 6pac** [comment] 2016-07-09 01:55
i'm away till sun 17th so won't be getting to it real soon :-)

**Comment by 6pac** [comment] 2016-07-21 08:05
any luck?

**Comment by dedward3** [comment] 2016-07-27 17:36
Sorry, I got sidetracked on something else. I'll try and get to it this evening, or tomorrow morning.

**Comment by 6pac** [comment] 2016-08-19 08:14
Can you possibly tweak an example page to reproduce this behaviour?

**Comment by ghiscoding** [comment] 2023-05-29 15:15
closing since no feedback were provided and a lot had change since then we removed jQueryUI in v3.0 and we also removed jQuery in v4.0 which we just released (see [v4.0.0](https://github.com/6pac/SlickGrid/releases/tag/4.0.0) release)). Feel free to reopen by providing more details if it's still an issue

**Closed by ghiscoding** 2023-05-29 15:15 UTC
