### ISSUE TITLE
cellrangeselector : Slickgrid focus issue on cell range selection

### ISSUE THREAD

**Issue by saynala** [6pac/SlickGrid#288] opened 2018-11-21 20:42 UTC
Have focus off the grid somewhere in the application and using the cellrangeselector select a range of cells without clicking on the slickgrid and then notice the focus is not on the grid. Anyway to address this?

Since the focus is not on the grid anymore, the copy paste won't work. Tried grid.focus() but its not helping.

**Comment by ghiscoding** [comment] 2018-11-27 05:30
This is similar to your other opened issue and the answer is probably similar as well, see the [comment](https://github.com/6pac/SlickGrid/issues/280#issuecomment-440818157) left in the other issue #280.

**Comment by ghiscoding** [comment] 2023-09-27 15:12
closing since it's a duplicate of #280 and no feedback provided

**Closed by ghiscoding** 2023-09-27 15:12 UTC
