### ISSUE TITLE
Prevent cell content removal on click (when editor is used)

### ISSUE THREAD

**Issue by manju-reddys** [6pac/SlickGrid#11] opened 2015-07-02 18:20 UTC
Hello,

I have custom editor for cell, the problem i'm facing is whenever the cell is clicked the existing content (DOM) is getting removed and also I'm not able to listen to the events registered to the cell content DOM. Is there way I can prevent the cell content removed by default? how do I listen to the cell content DOM events?

![image](https://cloud.githubusercontent.com/assets/1906881/8484315/02397a46-20c5-11e5-936a-1fffccb0d3cc.png)

In the attached image, the 2 input boxes must show on clicking "Set Range" and if user click on the clear icon (red x circled) the cell content should set back to "Set Range". I have implemented using "grid.onClick.subscribe" but this have other challenges like validation. I couldn't use the editor because of the cell content getting cleared by default.

**Comment by 6pac** [comment] 2015-07-03 10:31
From your description of the problem, I suspect that you don't understand how the editors work.
Check out: example3a-compound-editors.html
You need to implement the editor separately from the formatter and then specify it in the column definition. The formatter result is cleared and the editor is created when you click on the cell - the formatter and editor are completely separate things and one should not activate the other.

**Comment by manju-reddys** [comment] 2015-07-06 15:46
Well, if my description is not clear I will explain here again:

As in attached image, I have requirement to clear the inputs (range) only when user click on the clear button (red circled). 

I understood the concept of formatter (how to render the value) and the editor (what to do on click), the problem what I'm talking about is how to prevent the content getting clear on click?. Before the editor init function get called the content is getting cleared.

To be more specific in the `slick.grid.js => Method "makeActiveCellEditable"` the condition 
```
// don't clear the cell if a custom editor is passed through
            if (!editor) {
                activeCellNode.innerHTML = "";
            }
```
How to set the parameter `editor` to true, so the content will be prevented to clear on click of the cell before the init method in the editor get called?

**Comment by 6pac** [comment] 2015-07-10 11:19
What I mean is that to keep it simple, you should write a formatter/editor pair that conforms to the normal behaviour of the grid editors. See example3a-compound-editors.html for a perfectly good range editor.
However, if you *must* do what you are trying to do, that requires a workaround of the default behaviour, and I think changes to the core code.

    function handleClick(e) {
      if (!currentEditor) {
        // if this click resulted in some cell child node getting focus,
        // don't steal it back - keyboard events will still bubble up
        // IE9+ seems to default DIVs to tabIndex=0 instead of -1, so check for cell clicks directly.
        if (e.target != document.activeElement || $(e.target).hasClass("slick-cell")) {
          setFocus();
        }
      }

      var cell = getCellFromEvent(e);
      if (!cell || (currentEditor !== null && activeRow == cell.row && activeCell == cell.cell)) {
        return;
      }

      trigger(self.onClick, {row: cell.row, cell: cell.cell}, e);
      if (e.isImmediatePropagationStopped()) {
        return;
      }

      if ((activeCell != cell.cell || activeRow != cell.row) && canCellBeActive(cell.row, cell.cell)) {
        if (!getEditorLock().isActive() || getEditorLock().commitCurrentEdit()) {
          scrollRowIntoView(cell.row, false);
          setActiveCellInternal(getCellNode(cell.row, cell.cell));
        }
      }
    }

by setting ```isImmediatePropagationStopped``` in the click event handler, you can then write a customised version of the final block. The problem is that while ```makeActiveCellEditable``` allows you to pass a custom editor object, ```setActiveCellInternal``` (which calls ```makeActiveCellEditable```) doesn't. So we'd have to either mod ```setActiveCellInternal``` or create some custom editor setting to allow suppressing of the cell clear.
It's difficult, and I'll have a think on the best way to do it.
I agree that it should be possible without modding core code. But it's a lot easier just to follow the existing behaviour.

**Comment by 6pac** [comment] 2015-07-10 11:58
OK, I've decided the best way to do this is to add a property ```suppressClearOnEdit``` to the editor itself. eg:

    function TextEditor(args) {
      var $input;
      var defaultValue;
      var scope = this;
      this.suppressClearOnEdit = true;

      this.init = function () {

I've then made ```makeActiveCellEditable``` check for that property:

      $(activeCellNode).addClass("editable");

      var useEditor = editor || getEditor(activeRow, activeCell);
	  
      // don't clear the cell if a custom editor is passed through
      if (!editor && !useEditor.suppressClearOnEdit) {
        activeCellNode.innerHTML = "";
      }
 
      currentEditor = new useEditor({

These changes have just been added to the repo [here](https://github.com/6pac/SlickGrid/commit/f8abd6d108a2dad509df50d604b61262dcc70dff). Let me know if it works for you.

**Comment by manju-reddys** [comment] 2015-07-10 18:55
This will not work because the variable "suppressClearOnEdit" is a  property of the editor function and we can get access to it only if we call the function. At this point the we haven't called the editor method so it will be undefined (not exposed).

The simplest and easiest way to solve this problem add property ("suppressClearOnEdit") to the column definition rather to trying access the method property.

![image](https://cloud.githubusercontent.com/assets/1906881/8626610/89d6f25e-2713-11e5-89fa-5885cabc4728.png)

**Comment by 6pac** [comment] 2015-07-12 01:20
Sorry, you are correct that the code as-is will not work. My bad.
The property needs to be assigned after the editor function, eg:

    function TextEditor(args) {
      var $input;
      var defaultValue;
      var scope = this;
    
      this.init = function () {
    ...
    
      this.init();
    }

    TextEditor.suppressClearOnEdit = true;

I still think this is a better approach, because the behaviour is part of the editor, and might be used in multiple columns, or columns might have editors dynamically reassigned.

**Comment by manju-reddys** [comment] 2015-07-13 16:10
I don't see the side effects of adding a variable to the column definition, its more flexible then this approach. This approach will fails if we define the editor as anonymous function.

**Comment by 6pac** [comment] 2015-07-14 01:18
I just think philosophically the behaviour is part of the editor, not the column. The only connection with the column is that the editor happens to have been assigned to it, and I want to avoid  creating more 'noise' in the column defaults if at all possible.

It would fail if the editor were anonymous, but why would you want to do that ?

**Closed** 2015-07-14 14:04 UTC

**Comment by manju-reddys** [comment] 2015-07-14 15:50
In my opinion: The configuration should be part of column definition, why? answer is simple, the editor is reusable component. The same editor can be in more than one column but each column may have different behaviors, it is not always true that the default operation (empty the cell) to be prevented in all columns, the editor is used. So I believe that adding it as column definition (config) is the best solution.

In my case, I use anonymous function (as editor) in case if no reusable code and not required complex logic. Like simple inline editing (just example - We can use the one comes with editor but can't customize it to our needs).

**Comment by 6pac** [comment] 2015-07-15 00:34
Look I'm sorry but I don't agree with any of these points.
The principle is that editors are a reusable plugin. As such, they should be named, live in a library file, and have consistent behaviour including clearing the cell.
You are welcome to change your own code, that is a trivial change, but in my opinion it is the role of the grid architecture to encourage good practices and provide a workable and consistent API.

So again, sorry, this is not a problem I have with you. As the gatekeeper for this project, consistency and simplicity are really important as they affect maintainability of the code, especially in team environments. It's easy to let requirements for flexibility turn the API into a hotchpotch of methods, when it's often better to make things slightly less flexible but architected in a way that promotes consistent program structure.
Those are the considerations I'm following, and I really think the solution provided is the best one for the main grid trunk. That's really all I have to say.

**Comment by manju-reddys** [comment] 2015-07-16 01:14
That is okay and thanks, I have already forked to go my way.
