### ISSUE TITLE
Unnecessary call to ensureIdUniqueness in slick.dataview.js:setItems

### ISSUE THREAD

**Issue by turchanov** [6pac/SlickGrid#238] opened 2018-05-02 11:52 UTC
Hi!

It really seems that a call to `ensureIdUniqueness` right after `updateIdxById()` is superfluous in `function setItems`
https://github.com/6pac/SlickGrid/blob/427e2bf9588f6b70b21845a3b46c720b4672b617/slick.dataview.js#L130-L139
because when the function `updateIdxById` traverses `items`, it checks that every data item has _id_ property defined and builds `idxById` array
https://github.com/6pac/SlickGrid/blob/427e2bf9588f6b70b21845a3b46c720b4672b617/slick.dataview.js#L104-L114
and the function `ensureIdUniqueness`  yet again checks checks that every data item has _id_ property defined and verifies that `idxById` references that item (which is true by construction in `updateIdxById`)
https://github.com/6pac/SlickGrid/blob/427e2bf9588f6b70b21845a3b46c720b4672b617/slick.dataview.js#L116-L124
I would rather remove that unnecessary call to `ensureIdUniqueness` and the definition of that function since it is not used anywere else. I can push a pull request if you OK that change.

**Comment by ghiscoding** [comment] 2023-05-13 05:35
closing since after trying the suggestion, the error is not thrown when we really have duplicate, so unfortunately the suggestion doesn't seem to be valid

**Closed by ghiscoding** 2023-05-13 05:35 UTC

**Comment by 6pac** [comment] 2023-05-14 06:37
I think the issue is that ```updateIdxById``` assigns the reverse lookup and if there are duplicates, the last one wins and the previous references to that ID are overwritten. ```ensureIdUniqueness``` goes through and checks that the reverse lookups resolve correctly, which they won't if something has been overwritten.
