### ISSUE TITLE
Error while doing draggable grouping

### ISSUE THREAD

**Issue by nzhtrtlc** [6pac/SlickGrid#225] opened 2018-03-29 10:40 UTC
Hi, i am trying to implement draggable grouping into grid. But i get this error.

![image](https://user-images.githubusercontent.com/17534778/38084458-a56d986e-3355-11e8-8e22-a67c7f10b43f.png)

Here is what and how i imported  files.

![image](https://user-images.githubusercontent.com/17534778/38084504-c8196fa0-3355-11e8-8515-3b755a83cf4b.png)

Here is my code

> import React from 'react';
> import 'layout/assets/styles/slickgrid.scss';
> 
> class TestFile extends React.Component {
> 
>    componentDidMount() {
>       this.init();
>    }
> 
>    componentWillUnmount() {
>       this.grid = null;
>    }
> 
>    grid = null;
>    dataView = null;
>    options = {};
>    columns = [
>       {id: "sel", name: "#", field: "sel", cssClass: "cell-selection", width: 40, resizable: false, selectable: false, focusable: false,
>          grouping: {}
>       },
>       {id: "title", name: "Title", field: "title", width: 70, minWidth: 50, cssClass: "cell-title", sortable: true,
>          grouping: {
>             getter: "title",
>             formatter: function (g) {
>                return "Title:  " + g.value + "  <span style='color:green'>(" + g.count + " items)</span>";
>             },
>             aggregators: [
>                new Slick.Data.Aggregators.Sum("cost")
>             ],
>             aggregateCollapsed: false,
>             collapsed: false
>          }
>       },
>       {id: "duration", name: "Duration", field: "duration", width: 70, sortable: true,
>          grouping: {
>             getter: "duration",
>             formatter: function (g) {
>                return "Duration:  " + g.value + "  <span style='color:green'>(" + g.count + " items)</span>";
>             },
>             aggregators: [
>                new Slick.Data.Aggregators.Sum("cost")
>             ],
>             aggregateCollapsed: false,
>             collapsed: false
>          }
>       },
> 
>       {id: "start", name: "Start", field: "start", minWidth: 60, sortable: true,
>          grouping: {
>             getter: "start",
>             formatter: function (g) {
>                return "Start:  " + g.value + "  <span style='color:green'>(" + g.count + " items)</span>";
>             },
>             aggregators: [
>                new Slick.Data.Aggregators.Sum("cost")
>             ],
>             aggregateCollapsed: false,
>             collapsed: false
>          }
>       },
>       {id: "finish", name: "Finish", field: "finish", minWidth: 60, sortable: true,
>          grouping: {
>             getter: "finish",
>             formatter: function (g) {
>                return "Finish:  " + g.value + "  <span style='color:green'>(" + g.count + " items)</span>";
>             },
>             aggregators: [
>                new Slick.Data.Aggregators.Sum("cost")
>             ],
>             aggregateCollapsed: false,
>             collapsed: false
>          }
>       },
>       {id: "cost", name: "Cost", field: "cost", width: 90, sortable: true,
>          grouping: {
>             getter: "cost",
>             formatter: function (g) {
>                return "Cost:  " + g.value + "  <span style='color:#497380'>(" + g.count + " items)</span>";
>             },
>             aggregators: [
>                new Slick.Data.Aggregators.Sum("cost")
>             ],
>             aggregateCollapsed: false,
>             collapsed: false
>          }
>       },
>       {id: "effortDriven", name: "Effort Driven",  width: 80, minWidth: 20, maxWidth: 80, cssClass: "cell-effort-driven", field: "effortDriven", formatter: Slick.Formatters.Checkmark, sortable: true,
>          grouping: {
>             getter: "effortDriven",
>             formatter :function (g) {
>                return "Effort-Driven:  " + (g.value ? "True" : "False") + "  <span style='color:green'>(" + g.count + " items)</span>";
>             },
>             aggregators: [
>                new Slick.Data.Aggregators.Sum("cost")
>             ],
>             collapsed: false
>          }
>       }
>    ];
> 
> 
>    init = () => {
>       let draggableGrouping = new Slick.DraggableGrouping({
>          iconImage: '3rdParty/slickgrid/images/delete.png',
>          groupIconImage: '3rdParty/slickgrid/images/column-grouping.png',
>          dropPlaceHolderText: 'Drop a column header here to group by the column :)'
>       });
>       this.options = {
>          enableCellNavigation: true,
>          enableColumnReorder: draggableGrouping.getSetupColumnReorder,
>          createPreHeaderPanel: true,
>          showPreHeaderPanel: true,
>          preHeaderPanelHeight: 25
>       };
>       let groupItemMetadataProvider = new Slick.Data.GroupItemMetadataProvider();
>       this.dataView = new Slick.Data.DataView({
>          groupItemMetadataProvider: groupItemMetadataProvider,
>          inlineFilters: true
>       });
>       this.loadData();
>       this.grid = new Slick.Grid('#myGrid', this.dataView, this.columns, this.options);
>       this.grid.registerPlugin(groupItemMetadataProvider);
>       this.grid.registerPlugin(draggableGrouping);
>    };
> 
>    loadData() {
>       const data = [];
>       for (let i = 0; i < 500; i++) {
>          data[i] = {
>             id: i,
>             title: 'Task ' + i,
>             duration: '5 days',
>             start: '01/01/2009',
>             finish: '01/05/2009',
>             cost: Math.round(Math.random() * 100),
>             effortDriven: (i % 5 == 0)
>          };
>       }
>       this.dataView.setItems(data);
>    }
> 
>    render() {
>       return (
>          <div id="myGrid" style={{ width: 600, height: 500, fontFamily: 'arial', fontSize: '8pt' }}/>
>       )
>    }
> }
> 
> export default TestFile;

**Comment by nzhtrtlc** [comment] 2018-03-29 11:26
This issue was caused by
 `     aggregators: [
               new Slick.Data.Aggregators.Sum("cost")
            ],`
this piece of code. I removed all aggregators from my columns and it worked. I don't know why i get this error when i want to implement aggregator too. Any ideas ?

**Comment by 6pac** [comment] 2018-03-29 12:06
It appears that the problem is in ```compileAccumulatorLoop``` inside ```slick.dataview.js```. 

    function compileAccumulatorLoop(aggregator) {
      var accumulatorInfo = getFunctionInfo(aggregator.accumulate);
      var fn = new Function(
          "_items",
          "for (var " + accumulatorInfo.params[0] + ", _i=0, _il=_items.length; _i<_il; _i++) {" +
              accumulatorInfo.params[0] + " = _items[_i]; " +
              accumulatorInfo.body +
          "}"
      );
      fn.displayName = fn.name = "compiledAccumulatorLoop";
      return fn;
    }

There is probably a problem with ```new Function``` conflicting with React or Node. Not sure what, though.

https://davidwalsh.name/new-function

**Comment by muthukumarse** [comment] 2018-03-29 14:08
@nzhtrtlc - good you found it. aggregators you should try with your own function.

@6pac  - i am using slickgrid with React, i don't face any issue. Actually we developed a component which pipe from react to slickgrid jquery

**Comment by nzhtrtlc** [comment] 2018-03-29 14:16
@muthukumarse I am working with react too. But i use it in very basic level. I imported all the jquery and slickgrid files in my index.js then i can use it in my pages.
What kind of implementation did you do ? 
For example: Can you render your own formatters for slickgrid ?
like;
formatter: props => <span style={{color: 'green'}}> {props.value}</span>

**Comment by muthukumarse** [comment] 2018-03-29 14:37
@nzhtrtlc - yes you can do that.
For Row 
--------
on Init Grid you have to register this
dataView.getItemMetadata = rowFormatter(dataView.getItemMetadata, dataView);
then you can define rowFormatter function
rowFormatter: (dataItem, dataView) => (row) => {
          const item = dataView.getItem(row);
          const ret = dataItem(row) || {};

          if (item) {
            ret.cssClasses = ret.cssClasses || '';
            if (item.active === 'N') {
              ret.cssClasses += 'disabled-row';
            }
          }
          return ret;
        }


for Column
-----------

where you can define formatter function on define colums

columns: [
      id: xxx,
      name: xxx, ....
      formatter: (row, cell, value) => {
        if (value === 'Enabled') {
          return `<span style="color:red">${value}</span>`;
        } else if (value === 'Disabled') {
          return `<span style="color:green">${value}</span>`;
        }
        return value;
      }
  ]

**Comment by nzhtrtlc** [comment] 2018-03-29 15:18
@muthukumarse It does not work.

my init function to set options for grid. you can check the comment with the green line
![image](https://user-images.githubusercontent.com/17534778/38097124-323d78f0-337d-11e8-8488-dbd5bbbdd8d7.png)

formatter for the column. if condition renders jsx else condition renders normal web element in string.
![image](https://user-images.githubusercontent.com/17534778/38097135-3be4ddb2-337d-11e8-92e7-4049ed38f5c2.png)

the result
![image](https://user-images.githubusercontent.com/17534778/38097145-432e4518-337d-11e8-8c16-b481f915cd6d.png)

**Comment by muthukumarse** [comment] 2018-03-30 01:00
@nzhtrtlc - I see your column formatter working as expected. Now what is error while trying to drag the column to group ?

**Comment by nzhtrtlc** [comment] 2018-04-02 07:43
@muthukumarse I solved that. I have no problem with draggable grouping or aggregating.
I was just curious if i can use formatter function like jsx.
Please check the **formatter** function of **effortDriven** column (2nd screenshot). 
This cell takes two values (TRUE OR FALSE )
There is a condition.. if value is true then try to render as jsx otherwise render in as string.
When i run this code only false condition works as expected, because i can not render react component in formatter function. This is not an issue because SlickGrid is not using react. I just wanted to learn if i can render react component in formatters. And i thought you could render react component in formatter function somehow but i think you couldn't either, couldn't you ?

**Comment by muthukumarse** [comment] 2018-04-02 08:54
@nzhtrtlc - you can do that

my case like this
```

grouping: {
      formatter = (g) => `${column.label}: ${g.value}<span style='color:#007dba;'> (${g.count})</span>`
    }
```

in your case you should try this

grouping: {
      formatter = (g) => `Effort Driven: ${column.label}: ${g.value ?  'True': 'False'}<span style='color:green;'> (${g.count})</span>`
    }

**Comment by nzhtrtlc** [comment] 2018-04-02 10:55
@muthukumarse You are using es6 template literals which is good alternative. But still you are not using jsx. 

This is what am i talking about
`formatter: (g) => <span className="myclassname">Effort Driven:  {g.value}</span>`

(*Not using any strings. Renders directly the element*)

We can not do that because SlickGrid is not using react. 
Anyway thank you for your help.

**Comment by muthukumarse** [comment] 2018-04-02 11:01
@6pac - can we close this issue.

**Closed** 2018-04-02 11:34 UTC
