### ISSUE TITLE
Frozen/Pinned columns

### ISSUE THREAD

**Issue by psinghsp** [6pac/SlickGrid#258] opened 2018-07-05 20:40 UTC
Are there any plans to incorporate frozen/pinned columns? I saw some other forks which implement this - but I do not know if this can be implemented in conjunction with column reorder plugin and other plugins controlling other column properties.

**Comment by ghiscoding** [comment] 2018-07-05 21:57
duplicate of #26 
Please follow it the discussion there, thanks

**Closed by ghiscoding** 2018-07-05 21:57 UTC
