### ISSUE TITLE
Header/footer cell sizes broken when using fullWidthRows:true

### ISSUE THREAD

**Issue by yamass** [6pac/SlickGrid#699] opened 2022-09-28 17:19 UTC
### When does it happen?

Whenever you configure the following:
```js
    fullWidthRows: true,
    showHeaderRow: true
```
Or the corresponding options for the footer row:
```js
    fullWidthRows: true, 
    createFooterRow: true,
    showFooterRow: true,
```

### Example (minimalistic)

(put this into the examples directory to run)

```html
<!DOCTYPE html>
<html lang="en" style="height: 100%">
<head>
  <link rel="stylesheet" href="../slick.grid.css" type="text/css">
  <link rel="stylesheet" href="../slick-default-theme.css" type="text/css">
  <script src="../lib/jquery-3.1.0.js"></script>
  <script src="../lib/jquery-ui-1.9.2.js"></script>
  <script src="../lib/jquery.event.drag-2.3.0.js"></script>
  <script src="../slick.core.js"></script>
  <script src="../slick.dataview.js"></script>
  <script src="../slick.grid.js"></script>
</head>
<body style="height: 100%">

<div id="grid" style="width: 100%; height: 100%"></div>

<script>

  let grid = new Slick.Grid("#grid", [
    {a:"a1", b:"b1"},
    {a:"a2", b:"b2"}
  ], [
    {id: "a", field: "a", name: "a"},
    {id: "b", field: "b", name: "b"}
  ], {
    fullWidthRows: true, // !!
    showHeaderRow: true,
    createFooterRow: true,
    showFooterRow: true,
    explicitInitialization: true
  });

  grid.onHeaderRowCellRendered.subscribe((e, args) => {
    // this will make the first column red and the second blue (half-transparent), so you can see the problem.
    args.node.style.backgroundColor = args.column.name === "a" ? "red" : "rgba(0, 0, 255, .5)";
  });
  grid.onFooterRowCellRendered.subscribe((e, args) => {
    // this will make the first column red and the second blue (half-transparent), so you can see the problem.
    args.node.style.backgroundColor = args.column.name === "a" ? "red" : "rgba(0, 0, 255, .5)";
  });

  grid.init();

</script>
</body>
</html>
```

Wrong:
![localhost_63342_SlickGrid_examples_example1-simple html__ijt=hf7kmrlafo8ir09kj0ogcivllf _ij_reload=RELOAD_ON_SAVE](https://user-images.githubusercontent.com/275410/192847478-8097528c-bf7a-4fb4-8057-d3a14c4bc05d.png)

Right: 
![localhost_63342_SlickGrid_examples_example1-simple html__ijt=hf7kmrlafo8ir09kj0ogcivllf _ij_reload=RELOAD_ON_SAVE (1)](https://user-images.githubusercontent.com/275410/192847511-91937893-368e-4454-aad1-f6f0e091b004.png)

I figured out that `$headerRowL.width` is erroneously set to `canvasWidth`, which is incorrect. It should be `canvasWidthL`.
The same issue holds for the footer, too. 

I will create a pull request with a fix.

**Comment by ghiscoding** [comment] 2022-11-12 18:15
@yamass I tried your minimalistic example and I don't see any issues, I took the AutoTooltip Example and replaced the code with what you provided and it seems fine as shown below

![image](https://user-images.githubusercontent.com/643976/201488758-30497345-bf33-4a8b-8c53-730efb85f7ea.png)

**Comment by ghiscoding** [comment] 2023-05-15 17:36
closing since I could not reproduce and the codebase changed a lot since then and will change even more when [Roadmap to v4.0](https://github.com/6pac/SlickGrid/discussions/743) is officially released

**Closed by ghiscoding** 2023-05-15 17:36 UTC
