### ISSUE TITLE
Frozen Column right to left

### ISSUE THREAD

**Issue by codezgy** [6pac/SlickGrid#739] opened 2023-03-21 06:36 UTC
i want to pin (right)  somes columns，what should I do？

**Comment by ghiscoding** [comment] 2023-03-21 13:42
duplicate of #410, it's simply not supported because of its complexity

**Comment by codezgy** [comment] 2023-03-22 07:19
Okay, I got it. Thank you.

**Closed** 2023-05-06 12:13 UTC

**Comment by islittlezhou** [comment] 2026-01-09 11:31
Is there a solution? Freezing the right side of the column is very important to me。
Why is the table only implemented with the left column frozen, but not the right column? Is it due to the underlying design not supporting it?
