### ISSUE TITLE
Scrolling with many lines creates some jumps

### ISSUE THREAD

**Issue by ISMaxM** [6pac/SlickGrid#590] opened 2021-03-25 14:56 UTC
There's a page system to handle the case where the navigator can't display enougth height to display all the lines. It depends on the navigator. For instance, chrome can display 1M lines. But when I scroll around the 1Mth line, I often jump around 2k lines with one scroll. 

I reproduced that by modifying the 1st example and creating 1.5M lines. 

<script>
  var grid;
  var columns = [
    {id: "title", name: "Title", field: "title"},
  ];

  var options = {
    enableCellNavigation: true,
    enableColumnReorder: false
  };

  $(function () {
    var data = [];
    for (var i = 0; i < 1250000; i++) {
      data[i] = {
        title: "Task " + i,
      };
    }

    grid = new Slick.Grid("#myGrid", data, columns, options);
  })
</script>

**Comment by ghiscoding** [comment] 2021-03-25 15:03
duplicate of #297

**Comment by ghiscoding** [comment] 2021-05-25 13:40
closing since it's a duplicate, 1 opened story is enough to keep track

**Closed by ghiscoding** 2021-05-25 13:40 UTC
