### ISSUE TITLE
A bug was detected during the SlickGrid test

### ISSUE THREAD

**Issue by BBongSu** [6pac/SlickGrid#1027] opened 2024-06-17 04:22 UTC
### Describe the bug

To be specific, as you can see on the screenshot screen, raise or lower the scroll bar

Controlling the mouse wheel causes data to be cut off.

The same phenomenon occurs in the sample file.

Is it possible to solve it quickly?

The framework is currently using spring boot 3.2 and jQuery version is 3.6

### Reproduction

![image](https://github.com/6pac/SlickGrid/assets/123544693/73c0fe2d-e942-418c-859e-d859de931b7a)

### Which Framework are you using?

Angular

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| SlickGrid | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/6pac/SlickGrid/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/6pac/SlickGrid/wiki).
- [X] Check that there isn't [already an issue](https://github.com/6pac/SlickGrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/6pac/SlickGrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment] 2024-06-18 19:00
Calling `grid.invalidate()` when that happens would probably fix the problem. However the biggest challenge would be to detect when that happens, I don't think that we have any correct way to detect such issues in the UI. 

Also the latest version of SlickGrid no longer requires jQuery (since v4), you should consider removing it eventually. You did not include the version number that you used, even though it's part of the issue template (these info can help troubleshooting issues so please fill them next time).

**Comment by 6pac** [comment] 2024-06-19 01:00
Just FYI there used to be a Mousewheel bug fix in the code, but I think it was removed a while back since it related to bugs in old browsers. May not be relevant, but thought I'd mention it.

**Comment by ghiscoding** [comment] 2024-06-27 19:18
closing since cannot reproduce and no repro, neither feedback provided. We can reopen when a full repro is provided

**Closed by ghiscoding** 2024-06-27 19:18 UTC
Labels: need repro
