### ISSUE TITLE
CheckboxSelectColumn plugin breaks the onDblClick event

### ISSUE THREAD

**Issue by peterjoh** [6pac/SlickGrid#81] opened 2017-01-26 15:10 UTC
When using the CheckboxSelectColumn plugin, it invalidates the clicked row so that the double click event doesn't trigger. edit: I have a possible fix that seems to work, in my fork.

**Comment by 6pac** [comment] 2017-01-27 02:33
can you be clear about the order of events to reproduce this: you are clicking the checkbox, then where are you double clicking? There have been a number of comments about this example, I'll take a look soon.

**Comment by peterjoh** [comment] 2017-01-27 07:49
I noticed it occurring when double clicking somewhere else on the row, not on the checkbox. So the error seems to be in the function handleSelectedRowsChanged, slick.checkboxselectcolumn.js:37. My fix consists of inserting this line

`if (!lookup[i])`

on line 49.

**Comment by 6pac** [comment] 2018-03-23 23:07
Seems to be working fine at the moment. There have been a few fixes for edge cases lately, so I'm going to close this. If it's still a problem please re-open and provide a clear set of steps to reproduce, including the example URL and the browser.

**Closed by 6pac** 2018-03-23 23:07 UTC
